
DROP TABLE IF EXISTS allatok;
CREATE TABLE allatok (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nev VARCHAR(50) NOT NULL,
  faj VARCHAR(20) NOT NULL,
  fajta VARCHAR(80) NOT NULL,
  kor_honap INT NOT NULL,
  nem VARCHAR(10) NOT NULL,
  menhely_varos VARCHAR(60) NOT NULL,
  bekerules_datum DATE NOT NULL,
  statusz VARCHAR(30) NOT NULL,
  megjegyzes VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

INSERT INTO allatok (nev, faj, fajta, kor_honap, nem, menhely_varos, bekerules_datum, statusz, megjegyzes) VALUES
('Riley','kutya','keverék',72,'kan','Pécs','2023-05-23','örökbefogható','Játékos, tanulékony.'),
('Nala','macska','házi rövidszőrű',9,'hím','Pécs','2023-08-27','örökbefogható','Barátságos, pórázon szépen sétál.'),
('Zsömi','kutya','mudi keverék',141,'szuka','Pécs','2024-04-04','örökbefogható','Barátságos, pórázon szépen sétál.'),
('Kormi','kutya','mudi keverék',110,'szuka','Győr','2023-06-09','örökbefogható','Lakásba is ajánlott.'),
('Bella','kutya','tacskó',26,'szuka','Zalaegerszeg','2023-12-19','örökbefogható','Barátságos, pórázon szépen sétál.'),
('Gombóc','macska','vörös',33,'nőstény','Szeged','2024-07-19','örökbefogható','Lakásba is ajánlott.'),
('Nala','kutya','mudi keverék',19,'kan','Eger','2023-08-22','gazdis','Játékos, tanulékony.'),
('Picur','kutya','német juhász keverék',27,'szuka','Győr','2024-04-09','örökbefogható','Lakásba is ajánlott.'),
('Charlie','macska','fekete',55,'nőstény','Veszprém','2023-03-15','örökbefogható','Kezdetben félénk, türelmet igényel.'),
('Bogyó','macska','házi rövidszőrű',60,'hím','Sopron','2023-11-20','örökbefogható','Játékos, tanulékony.'),
('Max','macska','cirmos',65,'nőstény','Veszprém','2024-08-21','örökbefogható','Aktív, sok mozgást igényel.'),
('Panda','kutya','labrador keverék',132,'szuka','Szeged','2023-02-18','gazdis','Kezdetben félénk, türelmet igényel.'),
('Riley','kutya','német juhász keverék',110,'kan','Kecskemét','2024-01-26','örökbefogható','Nyugodt természetű.'),
('Csoki','macska','vörös',4,'hím','Eger','2024-07-03','gazdis','Lakásba is ajánlott.'),
('Bella','macska','tarka',42,'nőstény','Budapest','2023-09-27','orvosi megfigyelés','Kezdetben félénk, türelmet igényel.'),
('Csoki','kutya','német juhász keverék',78,'kan','Debrecen','2024-01-18','gazdis','Barátságos, pórázon szépen sétál.'),
('Szofi','macska','tarka',6,'hím','Tatabánya','2024-01-07','gazdis','Más állatokkal összeszoktatható.'),
('Zokni','kutya','labrador keverék',147,'kan','Szeged','2024-05-12','gazdis','Kezdetben félénk, türelmet igényel.'),
('Bella','kutya','labrador keverék',18,'szuka','Budapest','2024-08-25','örökbefogható','Gyerekek mellett is jól érzi magát.'),
('Bodri','kutya','mudi keverék',17,'kan','Szeged','2023-02-02','gazdis','Játékos, tanulékony.'),
('Csoki','kutya','vizsla keverék',126,'kan','Nyíregyháza','2023-05-16','örökbefogható','Nyugodt természetű.'),
('Zokni','macska','tarka',50,'hím','Szeged','2024-03-17','örökbefogható','Aktív, sok mozgást igényel.'),
('Zokni','kutya','labrador keverék',139,'szuka','Debrecen','2024-03-08','örökbefogható','Nyugodt természetű.'),
('Zokni','kutya','tacskó',142,'kan','Budapest','2024-07-07','gazdis','Játékos, tanulékony.'),
('Hópihe','kutya','labrador keverék',106,'szuka','Székesfehérvár','2023-08-07','gazdis','Barátságos, pórázon szépen sétál.'),
('Charlie','macska','házi rövidszőrű',101,'nőstény','Tatabánya','2024-04-10','örökbefogható','Nyugodt természetű.'),
('Max','kutya','vizsla keverék',57,'kan','Szombathely','2024-07-09','örökbefogható','Lakásba is ajánlott.'),
('Morzsi','kutya','border collie',124,'kan','Budapest','2024-06-04','örökbefogható','Kezdetben félénk, türelmet igényel.'),
('Szofi','kutya','tacskó',151,'szuka','Tatabánya','2023-09-25','örökbefogható','Lakásba is ajánlott.'),
('Zokni','macska','tarka',35,'nőstény','Székesfehérvár','2023-11-20','orvosi megfigyelés','Játékos, tanulékony.'),
('Bodri','macska','vörös',146,'hím','Szeged','2024-07-04','örökbefogható','Más állatokkal összeszoktatható.'),
('Max','macska','házi rövidszőrű',64,'nőstény','Győr','2023-06-11','örökbefogható','Más állatokkal összeszoktatható.'),
('Pötyi','kutya','keverék',143,'kan','Győr','2023-10-16','örökbefogható','Lakásba is ajánlott.'),
('Zizi','macska','házi rövidszőrű',2,'nőstény','Sopron','2023-05-14','örökbefogható','Más állatokkal összeszoktatható.'),
('Zsömi','kutya','német juhász keverék',96,'kan','Kecskemét','2023-05-11','örökbefogható','Lakásba is ajánlott.'),
('Tigris','kutya','vizsla keverék',55,'kan','Eger','2023-04-16','örökbefogható','Aktív, sok mozgást igényel.'),
('Tappancs','kutya','német juhász keverék',122,'kan','Pécs','2024-04-16','örökbefogható','Gyerekek mellett is jól érzi magát.'),
('Zokni','kutya','mudi keverék',51,'szuka','Miskolc','2023-10-13','gazdis','Más állatokkal összeszoktatható.'),
('Cirmi','macska','házi rövidszőrű',135,'hím','Miskolc','2024-03-17','örökbefogható','Lakásba is ajánlott.'),
('Szofi','macska','fehér',33,'nőstény','Nyíregyháza','2023-11-13','örökbefogható','Lakásba is ajánlott.'),
('Dió','kutya','tacskó',150,'szuka','Székesfehérvár','2024-03-28','örökbefogható','Gyerekek mellett is jól érzi magát.'),
('Csoki','macska','fehér',45,'hím','Győr','2024-06-11','örökbefogható','Lakásba is ajánlott.'),
('Luna','kutya','mudi keverék',81,'kan','Sopron','2023-07-23','örökbefogható','Barátságos, pórázon szépen sétál.'),
('Zokni','macska','vörös',20,'nőstény','Kecskemét','2024-10-06','örökbefogható','Aktív, sok mozgást igényel.'),
('Kókusz','macska','cirmos',39,'hím','Tatabánya','2023-04-20','gazdis','Gyerekek mellett is jól érzi magát.'),
('Maci','kutya','német juhász keverék',120,'szuka','Sopron','2024-03-29','örökbefogható','Aktív, sok mozgást igényel.'),
('Pötyi','macska','fekete',140,'hím','Debrecen','2023-06-04','örökbefogható','Kezdetben félénk, türelmet igényel.'),
('Cirmi','kutya','keverék',108,'szuka','Miskolc','2024-07-09','örökbefogható','Barátságos, pórázon szépen sétál.'),
('Maja','macska','tarka',151,'hím','Zalaegerszeg','2024-08-12','örökbefogható','Barátságos, pórázon szépen sétál.'),
('Panda','macska','tarka',109,'hím','Székesfehérvár','2023-08-13','örökbefogható','Nyugodt természetű.'),
('Bodri','macska','fekete',105,'hím','Zalaegerszeg','2024-04-23','orvosi megfigyelés','Barátságos, pórázon szépen sétál.'),
('Hópihe','macska','vörös',146,'hím','Szeged','2024-03-14','örökbefogható','Nyugodt természetű.'),
('Charlie','kutya','vizsla keverék',99,'szuka','Pécs','2024-04-10','örökbefogható','Aktív, sok mozgást igényel.'),
('Pötyi','macska','fekete',22,'nőstény','Budapest','2024-07-06','örökbefogható','Lakásba is ajánlott.'),
('Zokni','kutya','tacskó',31,'kan','Székesfehérvár','2023-09-20','gazdis','Kezdetben félénk, türelmet igényel.'),
('Zsömi','macska','fehér',96,'hím','Nyíregyháza','2023-12-16','örökbefogható','Aktív, sok mozgást igényel.'),
('Zizi','macska','házi rövidszőrű',112,'nőstény','Eger','2024-04-15','örökbefogható','Aktív, sok mozgást igényel.'),
('Füge','kutya','német juhász keverék',24,'szuka','Tatabánya','2024-04-06','örökbefogható','Nyugodt természetű.'),
('Kókusz','kutya','vizsla keverék',68,'szuka','Győr','2024-09-02','örökbefogható','Más állatokkal összeszoktatható.'),
('Zsömi','kutya','border collie',50,'kan','Pécs','2024-02-21','örökbefogható','Gyerekek mellett is jól érzi magát.'),
('Cirmi','macska','fehér',127,'nőstény','Sopron','2023-01-18','örökbefogható','Gyerekek mellett is jól érzi magát.'),
('Gombóc','kutya','vizsla keverék',32,'kan','Pécs','2023-08-10','örökbefogható','Más állatokkal összeszoktatható.'),
('Charlie','macska','házi rövidszőrű',138,'hím','Győr','2023-02-16','orvosi megfigyelés','Más állatokkal összeszoktatható.'),
('Cirmi','kutya','mudi keverék',127,'kan','Zalaegerszeg','2023-01-13','örökbefogható','Nyugodt természetű.'),
('Kókusz','macska','fekete',49,'hím','Győr','2024-05-04','örökbefogható','Játékos, tanulékony.'),
('Tappancs','macska','házi rövidszőrű',149,'hím','Debrecen','2023-06-02','gazdis','Más állatokkal összeszoktatható.'),
('Luna','kutya','keverék',144,'szuka','Szombathely','2024-09-02','gazdis','Gyerekek mellett is jól érzi magát.'),
('Charlie','kutya','labrador keverék',143,'kan','Debrecen','2023-01-03','örökbefogható','Nyugodt természetű.'),
('Dió','kutya','labrador keverék',75,'szuka','Veszprém','2024-04-09','örökbefogható','Gyerekek mellett is jól érzi magát.'),
('Hópihe','macska','fehér',152,'hím','Kecskemét','2023-04-28','örökbefogható','Kezdetben félénk, türelmet igényel.'),
('Hópihe','macska','cirmos',20,'hím','Debrecen','2023-11-11','örökbefogható','Más állatokkal összeszoktatható.'),
('Maci','kutya','tacskó',79,'szuka','Győr','2024-05-27','örökbefogható','Nyugodt természetű.'),
('Luna','macska','fekete',106,'nőstény','Miskolc','2023-04-18','gazdis','Lakásba is ajánlott.'),
('Füge','macska','fekete',31,'nőstény','Zalaegerszeg','2024-06-10','gazdis','Barátságos, pórázon szépen sétál.'),
('Riley','macska','házi rövidszőrű',54,'nőstény','Nyíregyháza','2023-05-15','orvosi megfigyelés','Nyugodt természetű.'),
('Maci','kutya','mudi keverék',41,'szuka','Tatabánya','2023-10-26','örökbefogható','Más állatokkal összeszoktatható.'),
('Samu','macska','tarka',64,'nőstény','Nyíregyháza','2023-05-29','örökbefogható','Kezdetben félénk, türelmet igényel.'),
('Picur','kutya','vizsla keverék',108,'szuka','Tatabánya','2024-06-03','örökbefogható','Barátságos, pórázon szépen sétál.'),
('Panda','macska','vörös',141,'nőstény','Székesfehérvár','2023-11-26','gazdis','Gyerekek mellett is jól érzi magát.'),
('Nala','macska','cirmos',107,'hím','Miskolc','2024-04-29','örökbefogható','Aktív, sok mozgást igényel.'),
('Picur','kutya','német juhász keverék',114,'kan','Nyíregyháza','2024-04-12','örökbefogható','Kezdetben félénk, türelmet igényel.'),
('Cirmi','kutya','tacskó',72,'kan','Győr','2023-08-17','gazdis','Barátságos, pórázon szépen sétál.'),
('Samu','macska','vörös',153,'hím','Nyíregyháza','2023-02-02','gazdis','Barátságos, pórázon szépen sétál.'),
('Gombóc','kutya','keverék',145,'kan','Győr','2024-10-27','örökbefogható','Más állatokkal összeszoktatható.'),
('Panda','macska','fehér',3,'nőstény','Tatabánya','2023-06-13','örökbefogható','Más állatokkal összeszoktatható.'),
('Hópihe','kutya','labrador keverék',57,'kan','Tatabánya','2023-12-11','gazdis','Barátságos, pórázon szépen sétál.'),
('Charlie','macska','házi rövidszőrű',90,'nőstény','Szeged','2023-09-28','gazdis','Nyugodt természetű.'),
('Cirmi','kutya','német juhász keverék',22,'szuka','Sopron','2023-10-28','örökbefogható','Lakásba is ajánlott.'),
('Füge','macska','tarka',13,'hím','Szombathely','2023-08-22','orvosi megfigyelés','Barátságos, pórázon szépen sétál.'),
('Gombóc','kutya','vizsla keverék',99,'kan','Kecskemét','2024-04-09','örökbefogható','Lakásba is ajánlott.'),
('Maja','macska','fehér',55,'nőstény','Szombathely','2023-10-01','örökbefogható','Barátságos, pórázon szépen sétál.'),
('Szofi','kutya','német juhász keverék',138,'kan','Székesfehérvár','2023-09-08','gazdis','Nyugodt természetű.'),
('Hópihe','macska','házi rövidszőrű',177,'hím','Miskolc','2023-02-27','gazdis','Aktív, sok mozgást igényel.'),
('Kókusz','kutya','vizsla keverék',70,'szuka','Debrecen','2023-08-05','örökbefogható','Lakásba is ajánlott.'),
('Zizi','macska','fehér',103,'nőstény','Zalaegerszeg','2024-10-20','orvosi megfigyelés','Gyerekek mellett is jól érzi magát.'),
('Csoki','kutya','labrador keverék',145,'kan','Sopron','2023-09-27','örökbefogható','Más állatokkal összeszoktatható.'),
('Max','macska','tarka',58,'nőstény','Eger','2024-06-05','orvosi megfigyelés','Barátságos, pórázon szépen sétál.'),
('Bodri','kutya','vizsla keverék',41,'kan','Szombathely','2023-06-13','örökbefogható','Más állatokkal összeszoktatható.'),
('Bogyó','macska','tarka',99,'nőstény','Szeged','2024-04-24','örökbefogható','Kezdetben félénk, türelmet igényel.'),
('Bella','kutya','német juhász keverék',176,'kan','Zalaegerszeg','2024-07-03','orvosi megfigyelés','Lakásba is ajánlott.');
